Datetime/Models/Test.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Datetime.Models
{
    public class Test
    {
        [DataType(DataType.Date)]
        [Required]
        public DateTime Datum_1_Pflichteingabe { get; set; }

        [DataType(DataType.Date)]
        public DateTime? Datum_2_Optional { get; set; }
    }
}

Datetime/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Datetime.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Datetime/Controllers/TestController.cs
using Datetime.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Datetime.Controllers
{
    public class TestController : Controller
    {
        //
        // GET: /Test/
        public ActionResult Index()
        {
            var test = new Test();
            return View(test);
        }

        [HttpPost]
        public ActionResult Save(Test test)
        {
            Debugger.Break();
            return Json(new { UserMessage = "", Success = true });
        }
	}
}

Datetime/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<div class="k-floatwrap">
    <div style="float: left">
        <p>Use this area to provide additional information.</p>
    </div>

    <div style="float: right">
        <h3>Telerik UI for ASP.NET MVC TreeView</h3>
        <p>
            Use this area to provide additional information.
        </p>

        @(Html.Kendo().TreeView()
        .Name("LinksTreeView")
        .Items(items =>
        {
            items.Add()
                .Text("Home")
                .Action("Index", "Home");
            items.Add()
                .Text("About")
                .Action("About", "Home");
            items.Add()
                .Text("Contact")
                .Action("Contact", "Home");
        })
    )
    </div>
</div>

Datetime/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<h3>Telerik UI for ASP.NET MVC TabStrip</h3>
<br />

    @(Html.Kendo().TabStrip()
        .Name("ContactsTabStrip")
        .Items(items =>
        {
            items.Add()
                .Text("Phone")
                .Selected(true)
                .Content(@<text>
                    <p>
                        <span style="font-weight:bold">Main:</span>
                        <span>425.555.0100</span>
                    </p>
                </text>)
                .ContentHtmlAttributes(new { style = "min-height: 200px" });
            items.Add()
                .Text("Email")
                .Content(@<text>
                    <p>
                        <span style="font-weight:bold">Support:</span>
                        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
                    </p>
                    <p>
                        <span style="font-weight:bold">Marketing:</span>
                        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
                    </p>
                </text>)
                .ContentHtmlAttributes(new { style = "min-height: 200px" });
            items.Add()
                .Text("Address")
                .Content(@<text>
                    <p>
                        One Microsoft Way<br />
                        Redmond, WA 98052-6399
                    </p>
                </text>)
                .ContentHtmlAttributes(new { style = "min-height: 200px" });
        })
    )

Datetime/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <h3>Telerik UI for ASP.NET MVC PanelBar</h3>
    <br />

    @(Html.Kendo().PanelBar()
        .Name("IntroPanelBar")
        .Items(items =>
        {
            items.Add()
                .Text("Getting Started")
                .Selected(true)
                .Expanded(true)
                .Content(@<text>
                    <p style="padding:0 1em; padding-top: 0.7em">
                        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that enables a clean 
                        separation of concerns and gives you full control over markup for enjoyable, agile development.
                    <a href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more…</a></p>
                </text>);
            items.Add()
                .Text("Get more libraries")
                .Content(@<text>
                    <p style="padding:0 1em; padding-top: 0.7em">
                        NuGet is a free Visual Studio extension that makes it easy to add, remove, and update 
                        libraries and tools in Visual Studio projects.
                    <a href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more…</a></p>
                </text>);
            items.Add()
                .Text("Web Hosting")
                .Content(@<text>
                    <p style="padding:0 1em; padding-top: 0.7em">
                        You can easily find a web hosting company that offers the right 
                        mix of features and price for your applications.
                    <a href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more…</a></p>
                </text>);
        })
    )
</div>

Datetime/Views/Shared/EditorTemplates/Currency.cshtml
@model decimal?

@(Html.Kendo().CurrencyTextBoxFor(m => m)      
      .HtmlAttributes(new {style="width:100%"})
      .Min(0)
)

Datetime/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime?

@(Html.Kendo().DatePickerFor(m => m))

Datetime/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?

@(Html.Kendo().DateTimePickerFor(m => m))

Datetime/Views/Shared/EditorTemplates/Email.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox" })

Datetime/Views/Shared/EditorTemplates/EmailAddress.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="email" })

Datetime/Views/Shared/EditorTemplates/GridForeignKey.cshtml
@model object
           
@(
 Html.Kendo().DropDownListFor(m => m)        
        .BindTo((SelectList)ViewData[ViewData.TemplateInfo.GetFullHtmlFieldName("") + "_Data"])
)

Datetime/Views/Shared/EditorTemplates/Integer.cshtml
@model int?

@(Html.Kendo().IntegerTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
      .Min(int.MinValue)
      .Max(int.MaxValue)
)

Datetime/Views/Shared/EditorTemplates/Number.cshtml
@model double?

@(Html.Kendo().NumericTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
)

Datetime/Views/Shared/EditorTemplates/Password.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="password" })

Datetime/Views/Shared/EditorTemplates/String.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox" })

Datetime/Views/Shared/EditorTemplates/Time.cshtml
@model DateTime?
           
@(Html.Kendo().TimePickerFor(m => m))

Datetime/Views/Shared/EditorTemplates/Url.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="url" })

Datetime/Views/Shared/_Culture.cshtml
@{
    // CultureInfo.CurrentCulture wird vom Browser "angefordert" und
    // ggf. in Application_AcquireRequestState auf en-US gesetzt falls wir diese
    // culture nicht liefern können
    var culture = System.Globalization.CultureInfo.CurrentCulture.ToString();
}

@* wir laden genau diejenige Culture die vom Browser angefordert wird! *@
<script src="@Url.Content("~/Scripts/kendo/2014.1.415/cultures/kendo.culture." + culture + ".min.js")"></script>
<script src="@Url.Content("~/Scripts/globalize/globalize.js")"></script>
<script src="@Url.Content("~/Scripts/globalize/cultures/globalize.culture." + culture + ".js")"></script>

<script type="text/javascript">
    // http://squadwuschel.wordpress.com/2012/12/09/mvc-client-datenvalidierung-fr-dd-mm-yyyy-mit-jquery-globalize/
    // http://afana.me/post/aspnet-mvc-internationalization.aspx
    jQuery.validator.methods.date = function(value, element) {
        return Globalize.parseDate(value);
    };

    jQuery.validator.methods.number = function(value, element) {
        if (Globalize.parseFloat(value)) {
            return true;
        }
    };

    kendo.culture("@culture");		 // kendo-culture
    Globalize.culture("@culture");	 // jquery-culture (validation)				    
</script>

Datetime/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Telerik MVC Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
	<link href="@Url.Content("~/Content/kendo/2014.1.415/kendo.common.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2014.1.415/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2014.1.415/kendo.default.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2014.1.415/kendo.dataviz.default.min.css")" rel="stylesheet" type="text/css" />
	<script src="@Url.Content("~/Scripts/kendo/2014.1.415/kendo.all.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo/2014.1.415/kendo.aspnetmvc.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Telerik MVC Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Html.Partial("_Culture")
</body>
</html>

Datetime/Views/Test/Index.cshtml
@model Datetime.Models.Test

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<script type="text/javascript">
    function onSaveClick() {
        var form = $("#test-form");
        if (form.valid()) {
            $.ajax({
                url: form.attr("action"),
                type: "POST",
                data: form.serialize(),
                success: function (response) {
                    // Doku003
                    if (response.UserMessage != '') {
                        // Plausiprüfung => Eingabe muss nachgebessert werden!
                        alert(response.UserMessage);
                    }
                }
            });
        }
    }
</script>

@using (Html.BeginForm("Save", "Test", FormMethod.Post, new { @class = "form-horizontal", id = "test-form", role = "form" }))
{
    <fieldset>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Datum_1_Pflichteingabe)
            </div>
            <div class="col-md-2">
                @(Html.Kendo().DatePickerFor(m => m.Datum_1_Pflichteingabe))
                @Html.ValidationMessageFor(m => m.Datum_1_Pflichteingabe)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Datum_2_Optional)
            </div>
            <div class="col-md-2">
                @(Html.Kendo().DatePickerFor(m => m.Datum_2_Optional))
                @Html.ValidationMessageFor(m => m.Datum_2_Optional)
            </div>
        </div>
    </fieldset>
    @(Html.Kendo().Button()
        .Name("btnSave")
        .Tag("a")
        .Events(ev => ev.Click("onSaveClick"))
        .Content("Save")
    )
}